### ISSUE TITLE
QUESTION: How to concat bit values together?

### ISSUE THREAD

**Issue by john-terrell** [samitbasu/rust-hdl#36]
Is there an easy mechanism to concat different bit values together?

If I have to bit values 0xAA and 0xBB and 0xC - how can I create 0xAABBC?   I can shift them manually, of course - is there a more succinct way?

**Comment by samitbasu** [comment]
Hi @john-terrell  - in `rust-hdl`, you can only shift and or them.  In `rhdl`, you can simply put them into a tuple.
