### ISSUE TITLE
QUESTION: Arithmetic shift right?

### ISSUE THREAD

**Issue by john-terrell** [samitbasu/rust-hdl#37]
I've seen comments that signed operations aren't supported.   I'm coming back to Rust-HDL after a bit and am looking again at using it for larger projects.   If signed operations aren't available yet, are there any workaround at this point for completing a simple ALU that needs an arithmetic right shift?

Thanks.

**Comment by samitbasu** [comment]
Hi @john-terrell  - `rhdl` has full support for signed and unsigned operations.  So using a signed type will give you a signed shift.  The same is true in `rust-hdl`.  If you look at the example [here](https://github.com/samitbasu/rust-hdl/blob/main/rust-hdl-widgets/src/mac_fir.rs), you will see examples of doing signed arithmetic using `rust-hdl`.
