### ISSUE TITLE
QUESTION: How does array indexing work with non-literal indices?

### ISSUE THREAD

**Issue by john-terrell** [samitbasu/rust-hdl#38]
I'm creating a register file such as:

gprs:   [DFF<Bits<XLEN>>; 31],

I can read a particular register using a literal index:

self.out.next = self.gprs[0].d.val();

This works fine but when I try to index using a signal:

rd:     Signal<In, Bits<5>>,

self.out.next = self.gprs[self.rd.val()].d.val();

It fails to compile with:

error[E0277]: the type `[rust_hdl::prelude::DFF<rust_hdl::prelude::Bits<XLEN>>]` cannot be indexed by `rust_hdl::prelude::Bits<5>`

**Comment by samitbasu** [comment]
Hi @john-terrell in `rhdl`, you can index using any unsigned bit vector.  In `rust-hdl` you need to call `.index()` on the value.  So try `self.rd.val().index()`.

HTH
